---
- name: Ensure the conf.d directory is present in the configuration folder
  file:
    path: "{{pg_conf_dir}}/conf.d"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0744
    
- name: Ensure the conf.d path is set as include in postgresql.conf
  lineinfile:
    path: "{{pg_conf_dir}}/postgresql.conf"
    regexp: "^include_dir = 'conf.d'"
    line: "include_dir = 'conf.d'"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0644
  
  
- name: Ship the custom postgresql.conf in conf.d
  template:
    src: postgresql.conf.j2
    dest: "{{pg_conf_dir}}/conf.d/postgresql.conf"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0644