---
- name: Create the postgresql data area
  file:
    path: "{{ item.value.data_area|default(data_area) }}/{{item.value.version}}/{{item.key}}"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    state: directory
    mode: 0700
  with_dict: "{{ pg_clusters}}"


- name: Create the postgresql wal area
  file:
    path: "{{ item.value.wal_area|default(wal_area) }}/{{item.value.version}}/{{item.key}}"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    state: directory
    mode: 0700
  with_dict: "{{ pg_clusters}}"


- name: Create the postgresql log directory
  file:
    path: "{{ item.value.log_directory|default(log_directory) }}"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    state: directory
    mode: 0744
  with_dict: "{{ pg_clusters}}"

- name: Initialise the postgresql clusters
  command: "pg_createcluster -l {{ item.value.log_directory|default(log_directory) }}/postgresql-{{item.value.version}}-{{item.key}}.log -p {{ item.value.params.port}} -d {{ item.value.data_area|default(data_area) }}/{{item.value.version}}/{{item.key}}  {{item.value.version}} {{item.key}}  -- -X {{ item.value.wal_area|default(wal_area) }}/{{item.value.version}}/{{item.key}}"
  args:
    creates: "{{ item.value.data_area|default(data_area) }}/{{item.value.version}}/{{item.key}}/PG_VERSION"
  with_dict: "{{ pg_clusters}}"


- name: Ensure the conf.d directory is present in the configuration folder
  file:
    path: "/etc/postgresql/{{item.value.version}}/{{item.key}}/conf.d"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0744
  with_dict: "{{ pg_clusters}}"

- name: Ensure the conf.d path is set as include in postgresql.conf
  lineinfile:
    path: "/etc/postgresql/{{item.value.version}}/{{item.key}}/postgresql.conf"
    regexp: "^include_dir = 'conf.d'"
    line: "include_dir = 'conf.d'"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0644
  with_dict: "{{ pg_clusters}}"

- name: Ship the custom postgresql.conf in conf.d
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{item.value.version}}/{{item.key}}/conf.d/postgresql.conf"
    owner: "{{ pg_osuser }}"
    group: "{{ pg_osgroup }}"
    mode: 0644
  with_dict: "{{ pg_clusters}}"


- name: Start the postgresql service
  service:
    name: postgresql
    state: started
