---
- name: Drop the postgresql clusters
  command: "pg_dropcluster {{item.value.version}} {{item.key}} --stop"
  with_dict: "{{ pg_clusters}}"

- name: Remove the postgresql directories
  file:
    path: "{{ item.value.data_area|default(data_area) }}/{{item.value.version}}/{{item.key}}"
    state: absent
  with_dict: "{{ pg_clusters}}"


- name: Remove the postgresql wal area
  file:
    path: "{{ item.value.wal_area|default(wal_area) }}/{{item.value.version}}/{{item.key}}"
    state: absent
  with_dict: "{{ pg_clusters}}"


- name: Remove the postgresql log directory
  file:
    path: "{{ item.value.log_directory|default(log_directory) }}/{{item.value.version}}/{{item.key}}"
    state: absent
  with_dict: "{{ pg_clusters}}"
