---
- name: create the ssh key pairs for the postgresql user
  user:
    name: "{{ pg_osuser }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
  register: usr
- name: Fetch the keys in the keys directory
  fetch:
    src: "{{ usr['home'] }}/.ssh/id_rsa.pub"
    dest: "keys/"


- name: setup the autorized_keys file on the servers with the public keys
  authorized_key:
    user: "{{ pg_osuser }}"
    state: present
    key: "{{ lookup('file', 'keys/'+ hostvars[item]['inventory_hostname'] +'/'+usr['home']+'/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ groups.dbserver }}"
    - "{{ groups.bckserver }}"

- name: populate known_hosts for the servers
  blockinfile:
    dest: "{{usr['home']}}/.ssh/known_hosts"
    create: yes
    state: present
    owner: "{{ pg_osuser }}"
    block: "{{ lookup('pipe', 'ssh-keyscan -T 10 ' ~ hostvars[item]['inventory_hostname']) }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items:
    - "{{ groups.dbserver }} + {{ groups.bckserver }}"
