---
- name: create the ssh key pairs for the postgresql user
  user:
    name: "{{ pg_osuser }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
  register: usr
- name: Fetch the keys in the keys directory
  fetch:
    src: "{{ usr['home'] }}/.ssh/id_rsa.pub"
    dest: "keys/"


- name: setup the autorized_keys file on the servers with the public keys
  authorized_key:
    user: "{{ pg_osuser }}"
    state: present
    key: "{{ lookup('file', 'keys/'+ hostvars[item]['inventory_hostname'] +'/'+usr['home']+'/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ groups.dbserver }}"
    - "{{ groups.bckserver }}"

- name: Add the servers keys to known_hosts
  known_hosts:
   name: "{{ hostvars[item]['inventory_hostname'] }}"
   key: "lookup('file', 'keys/'+ hostvars[item]['inventory_hostname'] +'/'+usr['home']+'/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ groups.dbserver }}"
    - "{{ groups.bckserver }}"
  become: true
  become_user: "{{ pg_osuser }}"
